import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextuiProviderWrapper } from "./providers";
import { ToastProvider } from "@/components/ui/toast-provider";
import { Providers } from "@/lib/Redux/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NextuiProviderWrapper>
            <ToastProvider>{children}</ToastProvider>
          </NextuiProviderWrapper>
        </body>
      </html>
    </Providers>
  );
}
